[2025-03-22T04:01:03.467+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-22T04:01:04.026+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather-data-pipeline.create_insert_fact_tables scheduled__2025-03-22T03:00:00+00:00 [queued]>
[2025-03-22T04:01:04.165+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather-data-pipeline.create_insert_fact_tables scheduled__2025-03-22T03:00:00+00:00 [queued]>
[2025-03-22T04:01:04.172+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-22T04:01:04.332+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): create_insert_fact_tables> on 2025-03-22 03:00:00+00:00
[2025-03-22T04:01:04.578+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=220) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-22T04:01:04.605+0000] {standard_task_runner.py:72} INFO - Started process 223 to run task
[2025-03-22T04:01:04.606+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather-data-pipeline', 'create_insert_fact_tables', 'scheduled__2025-03-22T03:00:00+00:00', '--job-id', '227', '--raw', '--subdir', 'DAGS_FOLDER/weather-data-pipeline.py', '--cfg-path', '/tmp/tmpgh7zm_if']
[2025-03-22T04:01:04.670+0000] {standard_task_runner.py:105} INFO - Job 227: Subtask create_insert_fact_tables
[2025-03-22T04:01:06.340+0000] {task_command.py:467} INFO - Running <TaskInstance: weather-data-pipeline.create_insert_fact_tables scheduled__2025-03-22T03:00:00+00:00 [running]> on host c25e9da6226b
[2025-03-22T04:01:06.943+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather-data-pipeline' AIRFLOW_CTX_TASK_ID='create_insert_fact_tables' AIRFLOW_CTX_EXECUTION_DATE='2025-03-22T03:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-22T03:00:00+00:00'
[2025-03-22T04:01:06.950+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-22T04:01:07.076+0000] {base.py:84} INFO - Retrieving connection 'rizqi-neon'
[2025-03-22T04:01:08.091+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-22T04:01:08.151+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-22T04:01:08.156+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=weather-data-pipeline, task_id=create_insert_fact_tables, run_id=scheduled__2025-03-22T03:00:00+00:00, execution_date=20250322T030000, start_date=20250322T040104, end_date=20250322T040108
[2025-03-22T04:01:13.492+0000] {job.py:229} INFO - Heartbeat recovered after 10.94 seconds
[2025-03-22T04:01:16.297+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-22T04:01:16.470+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-22T04:01:16.566+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
