[2025-03-21T22:00:12.673+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-21T22:00:12.694+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather-data-pipeline.create_insert_fact_tables scheduled__2025-03-21T21:00:00+00:00 [queued]>
[2025-03-21T22:00:12.705+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather-data-pipeline.create_insert_fact_tables scheduled__2025-03-21T21:00:00+00:00 [queued]>
[2025-03-21T22:00:12.706+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-21T22:00:12.718+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): create_insert_fact_tables> on 2025-03-21 21:00:00+00:00
[2025-03-21T22:00:12.725+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3874) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-21T22:00:12.727+0000] {standard_task_runner.py:72} INFO - Started process 3877 to run task
[2025-03-21T22:00:12.726+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather-data-pipeline', 'create_insert_fact_tables', 'scheduled__2025-03-21T21:00:00+00:00', '--job-id', '177', '--raw', '--subdir', 'DAGS_FOLDER/weather-data-pipeline.py', '--cfg-path', '/tmp/tmp8xstwx31']
[2025-03-21T22:00:12.729+0000] {standard_task_runner.py:105} INFO - Job 177: Subtask create_insert_fact_tables
[2025-03-21T22:00:12.979+0000] {task_command.py:467} INFO - Running <TaskInstance: weather-data-pipeline.create_insert_fact_tables scheduled__2025-03-21T21:00:00+00:00 [running]> on host c25e9da6226b
[2025-03-21T22:00:13.093+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather-data-pipeline' AIRFLOW_CTX_TASK_ID='create_insert_fact_tables' AIRFLOW_CTX_EXECUTION_DATE='2025-03-21T21:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-21T21:00:00+00:00'
[2025-03-21T22:00:13.095+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-21T22:00:13.114+0000] {base.py:84} INFO - Retrieving connection 'rizqi-neon'
[2025-03-21T22:00:13.460+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-21T22:00:13.473+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-21T22:00:13.473+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=weather-data-pipeline, task_id=create_insert_fact_tables, run_id=scheduled__2025-03-21T21:00:00+00:00, execution_date=20250321T210000, start_date=20250321T220012, end_date=20250321T220013
[2025-03-21T22:00:13.547+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-21T22:00:13.561+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
