[2025-03-22T03:52:45.088+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-22T03:52:45.192+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather-data-pipeline.fetch_weather_tomorrow scheduled__2025-03-22T02:00:00+00:00 [queued]>
[2025-03-22T03:52:45.220+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather-data-pipeline.fetch_weather_tomorrow scheduled__2025-03-22T02:00:00+00:00 [queued]>
[2025-03-22T03:52:45.221+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-22T03:52:45.319+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): fetch_weather_tomorrow> on 2025-03-22 02:00:00+00:00
[2025-03-22T03:52:45.381+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=76) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-22T03:52:45.436+0000] {standard_task_runner.py:72} INFO - Started process 83 to run task
[2025-03-22T03:52:45.573+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather-data-pipeline', 'fetch_weather_tomorrow', 'scheduled__2025-03-22T02:00:00+00:00', '--job-id', '215', '--raw', '--subdir', 'DAGS_FOLDER/weather-data-pipeline.py', '--cfg-path', '/tmp/tmpvnv6jps9']
[2025-03-22T03:52:45.585+0000] {standard_task_runner.py:105} INFO - Job 215: Subtask fetch_weather_tomorrow
[2025-03-22T03:52:48.188+0000] {task_command.py:467} INFO - Running <TaskInstance: weather-data-pipeline.fetch_weather_tomorrow scheduled__2025-03-22T02:00:00+00:00 [running]> on host c25e9da6226b
[2025-03-22T03:52:50.143+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather-data-pipeline' AIRFLOW_CTX_TASK_ID='fetch_weather_tomorrow' AIRFLOW_CTX_EXECUTION_DATE='2025-03-22T02:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-22T02:00:00+00:00'
[2025-03-22T03:52:50.145+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-22T03:52:54.030+0000] {python.py:240} INFO - Done. Returned value was:                datetime  ...                                id
0   2025-03-22 03:00:00  ...  eb42faae211398cdcbb90a26fdc32366
1   2025-03-22 04:00:00  ...  a18b86d83edecf96d945327ed8bb64ea
2   2025-03-22 05:00:00  ...  7e6c2f152d6ff4e11d2ea4e013cfd8f4
3   2025-03-22 06:00:00  ...  c7ed2c810f0879075c91ad5d0c644900
4   2025-03-22 07:00:00  ...  be2973f8180d73aea4ae7f2f85fd8565
..                  ...  ...                               ...
116 2025-03-26 23:00:00  ...  ed55b364a957e2276fee3b993254ac6c
117 2025-03-27 00:00:00  ...  4bd2a8a6a0ac1f90dd0747c863045e1c
118 2025-03-27 01:00:00  ...  2e020f6d2e9a6fb945361d0750537602
119 2025-03-27 02:00:00  ...  a7a39fe087acfa46a761ebdea71c69da
120 2025-03-27 03:00:00  ...  9a4d195f2d3ceda0d8e5ab506cc795b8

[121 rows x 6 columns]
[2025-03-22T03:52:54.341+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-22T03:52:54.346+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=weather-data-pipeline, task_id=fetch_weather_tomorrow, run_id=scheduled__2025-03-22T02:00:00+00:00, execution_date=20250322T020000, start_date=20250322T035245, end_date=20250322T035254
[2025-03-22T03:52:54.561+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-22T03:52:55.547+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2025-03-22T03:52:55.566+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-22T03:52:55.591+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
