[2025-03-21T18:35:56.917+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-21T18:35:56.977+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather-two-source.create_table_if_not_exists manual__2025-03-21T18:35:49.583747+00:00 [queued]>
[2025-03-21T18:35:57.003+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather-two-source.create_table_if_not_exists manual__2025-03-21T18:35:49.583747+00:00 [queued]>
[2025-03-21T18:35:57.004+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-21T18:35:57.039+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): create_table_if_not_exists> on 2025-03-21 18:35:49.583747+00:00
[2025-03-21T18:35:57.072+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1024) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-21T18:35:57.079+0000] {standard_task_runner.py:72} INFO - Started process 1026 to run task
[2025-03-21T18:35:57.077+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather-two-source', 'create_table_if_not_exists', 'manual__2025-03-21T18:35:49.583747+00:00', '--job-id', '112', '--raw', '--subdir', 'DAGS_FOLDER/weather-two-source.py', '--cfg-path', '/tmp/tmpssyy8fyc']
[2025-03-21T18:35:57.083+0000] {standard_task_runner.py:105} INFO - Job 112: Subtask create_table_if_not_exists
[2025-03-21T18:35:57.190+0000] {task_command.py:467} INFO - Running <TaskInstance: weather-two-source.create_table_if_not_exists manual__2025-03-21T18:35:49.583747+00:00 [running]> on host c25e9da6226b
[2025-03-21T18:36:00.628+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather-two-source' AIRFLOW_CTX_TASK_ID='create_table_if_not_exists' AIRFLOW_CTX_EXECUTION_DATE='2025-03-21T18:35:49.583747+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-21T18:35:49.583747+00:00'
[2025-03-21T18:36:00.637+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-21T18:36:00.728+0000] {base.py:84} INFO - Retrieving connection 'rizqi-neon'
[2025-03-21T18:36:01.792+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-21T18:36:01.828+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-21T18:36:01.830+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=weather-two-source, task_id=create_table_if_not_exists, run_id=manual__2025-03-21T18:35:49.583747+00:00, execution_date=20250321T183549, start_date=20250321T183556, end_date=20250321T183601
[2025-03-21T18:36:01.947+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-21T18:36:02.253+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2025-03-21T18:36:02.277+0000] {taskinstance.py:3901} INFO - 3 downstream tasks scheduled from follow-on schedule check
[2025-03-21T18:36:02.281+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
