[2025-03-21T17:42:03.310+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-21T17:42:03.381+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather-data-pipeline.fetch_weather_data manual__2025-03-21T17:41:52.732921+00:00 [queued]>
[2025-03-21T17:42:03.414+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather-data-pipeline.fetch_weather_data manual__2025-03-21T17:41:52.732921+00:00 [queued]>
[2025-03-21T17:42:03.415+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-21T17:42:03.443+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): fetch_weather_data> on 2025-03-21 17:41:52.732921+00:00
[2025-03-21T17:42:03.454+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=172) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-21T17:42:03.461+0000] {standard_task_runner.py:72} INFO - Started process 174 to run task
[2025-03-21T17:42:03.462+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather-data-pipeline', 'fetch_weather_data', 'manual__2025-03-21T17:41:52.732921+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/weather-data-pipeline.py', '--cfg-path', '/tmp/tmpy2dhu94c']
[2025-03-21T17:42:03.467+0000] {standard_task_runner.py:105} INFO - Job 57: Subtask fetch_weather_data
[2025-03-21T17:42:04.089+0000] {task_command.py:467} INFO - Running <TaskInstance: weather-data-pipeline.fetch_weather_data manual__2025-03-21T17:41:52.732921+00:00 [running]> on host c25e9da6226b
[2025-03-21T17:42:04.344+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather-data-pipeline' AIRFLOW_CTX_TASK_ID='fetch_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-21T17:41:52.732921+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-21T17:41:52.732921+00:00'
[2025-03-21T17:42:04.346+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-21T17:42:06.389+0000] {python.py:240} INFO - Done. Returned value was:                datetime  ...                                id
0   2025-03-22 00:00:00  ...  d141d7863df92d8589c38ada109e123d
1   2025-03-22 01:00:00  ...  9a76c33fd475d3dd15980ea9b0a6cf0f
2   2025-03-22 02:00:00  ...  bcecc2bcc96510667af038521c26a926
3   2025-03-22 03:00:00  ...  bfbcf0e41660e298c99997d3d53d7d1c
4   2025-03-22 04:00:00  ...  b50fabebec04f1c1ceae4f21a3c1fe62
..                  ...  ...                               ...
163 2025-03-28 19:00:00  ...  82bace31ccf535a12c230bd007e74e1f
164 2025-03-28 20:00:00  ...  68940bd488f1bb0d6b44dbc73aa42ae7
165 2025-03-28 21:00:00  ...  296be3fd5649c23a50f62c2636cca692
166 2025-03-28 22:00:00  ...  8757850d378d2c1fe6084046eab4c105
167 2025-03-28 23:00:00  ...  4dd715704408015a5d87f3a0c5434ae6

[168 rows x 6 columns]
[2025-03-21T17:42:06.790+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-21T17:42:06.791+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=weather-data-pipeline, task_id=fetch_weather_data, run_id=manual__2025-03-21T17:41:52.732921+00:00, execution_date=20250321T174152, start_date=20250321T174203, end_date=20250321T174206
[2025-03-21T17:42:06.904+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-21T17:42:06.921+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
