[2025-03-21T17:41:57.923+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-21T17:41:57.957+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather-data-pipeline.create_table_if_not_exists manual__2025-03-21T17:41:52.732921+00:00 [queued]>
[2025-03-21T17:41:57.973+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather-data-pipeline.create_table_if_not_exists manual__2025-03-21T17:41:52.732921+00:00 [queued]>
[2025-03-21T17:41:57.974+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-21T17:41:57.997+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): create_table_if_not_exists> on 2025-03-21 17:41:52.732921+00:00
[2025-03-21T17:41:58.009+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=161) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-21T17:41:58.013+0000] {standard_task_runner.py:72} INFO - Started process 170 to run task
[2025-03-21T17:41:58.016+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather-data-pipeline', 'create_table_if_not_exists', 'manual__2025-03-21T17:41:52.732921+00:00', '--job-id', '56', '--raw', '--subdir', 'DAGS_FOLDER/weather-data-pipeline.py', '--cfg-path', '/tmp/tmplfwefmi8']
[2025-03-21T17:41:58.024+0000] {standard_task_runner.py:105} INFO - Job 56: Subtask create_table_if_not_exists
[2025-03-21T17:41:58.147+0000] {task_command.py:467} INFO - Running <TaskInstance: weather-data-pipeline.create_table_if_not_exists manual__2025-03-21T17:41:52.732921+00:00 [running]> on host c25e9da6226b
[2025-03-21T17:42:00.007+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather-data-pipeline' AIRFLOW_CTX_TASK_ID='create_table_if_not_exists' AIRFLOW_CTX_EXECUTION_DATE='2025-03-21T17:41:52.732921+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-21T17:41:52.732921+00:00'
[2025-03-21T17:42:00.010+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-21T17:42:00.178+0000] {base.py:84} INFO - Retrieving connection 'rizqi-neon'
[2025-03-21T17:42:00.651+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-21T17:42:00.669+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-21T17:42:00.670+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=weather-data-pipeline, task_id=create_table_if_not_exists, run_id=manual__2025-03-21T17:41:52.732921+00:00, execution_date=20250321T174152, start_date=20250321T174157, end_date=20250321T174200
[2025-03-21T17:42:00.812+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-21T17:42:01.300+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-21T17:42:01.303+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
