[2025-03-21T17:54:02.034+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-21T17:54:02.111+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather-two-source.check_and_insert_data manual__2025-03-21T17:53:46.219569+00:00 [queued]>
[2025-03-21T17:54:02.171+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather-two-source.check_and_insert_data manual__2025-03-21T17:53:46.219569+00:00 [queued]>
[2025-03-21T17:54:02.174+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-21T17:54:02.256+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): check_and_insert_data> on 2025-03-21 17:53:46.219569+00:00
[2025-03-21T17:54:02.287+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=380) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-21T17:54:02.295+0000] {standard_task_runner.py:72} INFO - Started process 382 to run task
[2025-03-21T17:54:02.298+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather-two-source', 'check_and_insert_data', 'manual__2025-03-21T17:53:46.219569+00:00', '--job-id', '75', '--raw', '--subdir', 'DAGS_FOLDER/weather-two-source.py', '--cfg-path', '/tmp/tmp2oi91ogk']
[2025-03-21T17:54:02.311+0000] {standard_task_runner.py:105} INFO - Job 75: Subtask check_and_insert_data
[2025-03-21T17:54:02.857+0000] {task_command.py:467} INFO - Running <TaskInstance: weather-two-source.check_and_insert_data manual__2025-03-21T17:53:46.219569+00:00 [running]> on host c25e9da6226b
[2025-03-21T17:54:03.156+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather-two-source' AIRFLOW_CTX_TASK_ID='check_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-21T17:53:46.219569+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-21T17:53:46.219569+00:00'
[2025-03-21T17:54:03.162+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-21T17:54:03.280+0000] {base.py:84} INFO - Retrieving connection 'rizqi-neon'
[2025-03-21T17:54:05.496+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-21T17:54:05.515+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-21T17:54:05.516+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=weather-two-source, task_id=check_and_insert_data, run_id=manual__2025-03-21T17:53:46.219569+00:00, execution_date=20250321T175346, start_date=20250321T175402, end_date=20250321T175405
[2025-03-21T17:54:05.630+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-21T17:54:06.005+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-21T17:54:06.009+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
