[2025-03-21T21:00:01.474+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-21T21:00:01.495+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather-data-pipeline.fetch_weather_tomorrow scheduled__2025-03-21T20:00:00+00:00 [queued]>
[2025-03-21T21:00:01.506+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather-data-pipeline.fetch_weather_tomorrow scheduled__2025-03-21T20:00:00+00:00 [queued]>
[2025-03-21T21:00:01.506+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-21T21:00:01.523+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): fetch_weather_tomorrow> on 2025-03-21 20:00:00+00:00
[2025-03-21T21:00:01.536+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3042) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-21T21:00:01.539+0000] {standard_task_runner.py:72} INFO - Started process 3050 to run task
[2025-03-21T21:00:01.540+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather-data-pipeline', 'fetch_weather_tomorrow', 'scheduled__2025-03-21T20:00:00+00:00', '--job-id', '166', '--raw', '--subdir', 'DAGS_FOLDER/weather-data-pipeline.py', '--cfg-path', '/tmp/tmppkehdju8']
[2025-03-21T21:00:01.543+0000] {standard_task_runner.py:105} INFO - Job 166: Subtask fetch_weather_tomorrow
[2025-03-21T21:00:02.223+0000] {task_command.py:467} INFO - Running <TaskInstance: weather-data-pipeline.fetch_weather_tomorrow scheduled__2025-03-21T20:00:00+00:00 [running]> on host c25e9da6226b
[2025-03-21T21:00:02.316+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather-data-pipeline' AIRFLOW_CTX_TASK_ID='fetch_weather_tomorrow' AIRFLOW_CTX_EXECUTION_DATE='2025-03-21T20:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-21T20:00:00+00:00'
[2025-03-21T21:00:02.317+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-21T21:00:03.429+0000] {python.py:240} INFO - Done. Returned value was:                datetime  ...                                id
0   2025-03-21 21:00:00  ...  49bba3c3abf918a63c7a3a280494bbb5
1   2025-03-21 22:00:00  ...  f710bb6389cb3585aa7ee83fbb77578e
2   2025-03-21 23:00:00  ...  5fffff7f34aece608054205114f9cf26
3   2025-03-22 00:00:00  ...  7538d7f45898dd9869b1dbb01d6b1645
4   2025-03-22 01:00:00  ...  d1eb62f94b4fcbbf59b97ea4de39b8b3
..                  ...  ...                               ...
116 2025-03-26 17:00:00  ...  c815a1943112db8980f44034d9bc2fbc
117 2025-03-26 18:00:00  ...  72db1191d1a9970f9e337937fe6e1b3d
118 2025-03-26 19:00:00  ...  5835a17b9c49075ebeb71a1b3d8a9fcf
119 2025-03-26 20:00:00  ...  7ed42922be6f89b113e1b4d45703533b
120 2025-03-26 21:00:00  ...  3d4c05af0f0dd36bbdb99fec3724077b

[121 rows x 6 columns]
[2025-03-21T21:00:03.491+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-21T21:00:03.492+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=weather-data-pipeline, task_id=fetch_weather_tomorrow, run_id=scheduled__2025-03-21T20:00:00+00:00, execution_date=20250321T200000, start_date=20250321T210001, end_date=20250321T210003
[2025-03-21T21:00:03.563+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-21T21:00:03.786+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-21T21:00:03.800+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
