[2025-03-21T19:05:54.004+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-21T19:05:54.078+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather-data-pipeline.create_insert_fact_tables manual__2025-03-21T19:04:56.298692+00:00 [queued]>
[2025-03-21T19:05:54.106+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather-data-pipeline.create_insert_fact_tables manual__2025-03-21T19:04:56.298692+00:00 [queued]>
[2025-03-21T19:05:54.108+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-21T19:05:54.154+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): create_insert_fact_tables> on 2025-03-21 19:04:56.298692+00:00
[2025-03-21T19:05:54.169+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1511) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-21T19:05:54.173+0000] {standard_task_runner.py:72} INFO - Started process 1520 to run task
[2025-03-21T19:05:54.176+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather-data-pipeline', 'create_insert_fact_tables', 'manual__2025-03-21T19:04:56.298692+00:00', '--job-id', '150', '--raw', '--subdir', 'DAGS_FOLDER/weather-data-pipeline.py', '--cfg-path', '/tmp/tmpv08tow05']
[2025-03-21T19:05:54.181+0000] {standard_task_runner.py:105} INFO - Job 150: Subtask create_insert_fact_tables
[2025-03-21T19:05:54.757+0000] {task_command.py:467} INFO - Running <TaskInstance: weather-data-pipeline.create_insert_fact_tables manual__2025-03-21T19:04:56.298692+00:00 [running]> on host c25e9da6226b
[2025-03-21T19:05:55.129+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather-data-pipeline' AIRFLOW_CTX_TASK_ID='create_insert_fact_tables' AIRFLOW_CTX_EXECUTION_DATE='2025-03-21T19:04:56.298692+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-21T19:04:56.298692+00:00'
[2025-03-21T19:05:55.132+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-21T19:05:55.196+0000] {base.py:84} INFO - Retrieving connection 'rizqi-neon'
[2025-03-21T19:05:55.581+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-21T19:05:55.624+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-21T19:05:55.626+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=weather-data-pipeline, task_id=create_insert_fact_tables, run_id=manual__2025-03-21T19:04:56.298692+00:00, execution_date=20250321T190456, start_date=20250321T190554, end_date=20250321T190555
[2025-03-21T19:05:55.854+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-21T19:05:56.393+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-21T19:05:56.397+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
