[2025-03-21T19:00:36.254+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-21T19:00:36.374+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather-two-source.create_insert_dim_tables scheduled__2025-03-21T18:00:00+00:00 [queued]>
[2025-03-21T19:00:36.450+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather-two-source.create_insert_dim_tables scheduled__2025-03-21T18:00:00+00:00 [queued]>
[2025-03-21T19:00:36.460+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-21T19:00:37.603+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): create_insert_dim_tables> on 2025-03-21 18:00:00+00:00
[2025-03-21T19:00:37.654+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1347) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-21T19:00:37.664+0000] {standard_task_runner.py:72} INFO - Started process 1369 to run task
[2025-03-21T19:00:37.684+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather-two-source', 'create_insert_dim_tables', 'scheduled__2025-03-21T18:00:00+00:00', '--job-id', '127', '--raw', '--subdir', 'DAGS_FOLDER/weather-two-source.py', '--cfg-path', '/tmp/tmpu96arft9']
[2025-03-21T19:00:37.691+0000] {standard_task_runner.py:105} INFO - Job 127: Subtask create_insert_dim_tables
[2025-03-21T19:00:37.841+0000] {task_command.py:467} INFO - Running <TaskInstance: weather-two-source.create_insert_dim_tables scheduled__2025-03-21T18:00:00+00:00 [running]> on host c25e9da6226b
[2025-03-21T19:00:41.313+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather-two-source' AIRFLOW_CTX_TASK_ID='create_insert_dim_tables' AIRFLOW_CTX_EXECUTION_DATE='2025-03-21T18:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-21T18:00:00+00:00'
[2025-03-21T19:00:41.322+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-21T19:00:41.489+0000] {base.py:84} INFO - Retrieving connection 'rizqi-neon'
[2025-03-21T19:00:41.982+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-21T19:00:42.009+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-21T19:00:42.011+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=weather-two-source, task_id=create_insert_dim_tables, run_id=scheduled__2025-03-21T18:00:00+00:00, execution_date=20250321T180000, start_date=20250321T190036, end_date=20250321T190042
[2025-03-21T19:00:42.171+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-21T19:00:42.883+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2025-03-21T19:00:42.911+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-21T19:00:42.915+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
