[2025-03-22T03:53:21.161+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-22T03:53:21.206+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather-data-pipeline.create_insert_fact_tables scheduled__2025-03-22T02:00:00+00:00 [queued]>
[2025-03-22T03:53:21.235+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather-data-pipeline.create_insert_fact_tables scheduled__2025-03-22T02:00:00+00:00 [queued]>
[2025-03-22T03:53:21.236+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-22T03:53:21.274+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): create_insert_fact_tables> on 2025-03-22 02:00:00+00:00
[2025-03-22T03:53:21.289+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=102) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-22T03:53:21.296+0000] {standard_task_runner.py:72} INFO - Started process 106 to run task
[2025-03-22T03:53:21.293+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather-data-pipeline', 'create_insert_fact_tables', 'scheduled__2025-03-22T02:00:00+00:00', '--job-id', '219', '--raw', '--subdir', 'DAGS_FOLDER/weather-data-pipeline.py', '--cfg-path', '/tmp/tmpzclx63k1']
[2025-03-22T03:53:21.300+0000] {standard_task_runner.py:105} INFO - Job 219: Subtask create_insert_fact_tables
[2025-03-22T03:53:21.887+0000] {task_command.py:467} INFO - Running <TaskInstance: weather-data-pipeline.create_insert_fact_tables scheduled__2025-03-22T02:00:00+00:00 [running]> on host c25e9da6226b
[2025-03-22T03:53:22.038+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather-data-pipeline' AIRFLOW_CTX_TASK_ID='create_insert_fact_tables' AIRFLOW_CTX_EXECUTION_DATE='2025-03-22T02:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-22T02:00:00+00:00'
[2025-03-22T03:53:22.040+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-22T03:53:22.072+0000] {base.py:84} INFO - Retrieving connection 'rizqi-neon'
[2025-03-22T03:53:22.550+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-22T03:53:22.575+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-22T03:53:22.576+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=weather-data-pipeline, task_id=create_insert_fact_tables, run_id=scheduled__2025-03-22T02:00:00+00:00, execution_date=20250322T020000, start_date=20250322T035321, end_date=20250322T035322
[2025-03-22T03:53:22.684+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-22T03:53:23.002+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-22T03:53:23.007+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
