[2025-03-21T17:59:24.414+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-21T17:59:24.452+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather-two-source.fetch_weather_tomorrow manual__2025-03-21T17:59:13.800189+00:00 [queued]>
[2025-03-21T17:59:24.472+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather-two-source.fetch_weather_tomorrow manual__2025-03-21T17:59:13.800189+00:00 [queued]>
[2025-03-21T17:59:24.473+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-21T17:59:24.504+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): fetch_weather_tomorrow> on 2025-03-21 17:59:13.800189+00:00
[2025-03-21T17:59:24.519+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=445) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-21T17:59:24.523+0000] {standard_task_runner.py:72} INFO - Started process 450 to run task
[2025-03-21T17:59:24.525+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather-two-source', 'fetch_weather_tomorrow', 'manual__2025-03-21T17:59:13.800189+00:00', '--job-id', '77', '--raw', '--subdir', 'DAGS_FOLDER/weather-two-source.py', '--cfg-path', '/tmp/tmpgnxk8od8']
[2025-03-21T17:59:24.530+0000] {standard_task_runner.py:105} INFO - Job 77: Subtask fetch_weather_tomorrow
[2025-03-21T17:59:24.966+0000] {task_command.py:467} INFO - Running <TaskInstance: weather-two-source.fetch_weather_tomorrow manual__2025-03-21T17:59:13.800189+00:00 [running]> on host c25e9da6226b
[2025-03-21T17:59:25.162+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather-two-source' AIRFLOW_CTX_TASK_ID='fetch_weather_tomorrow' AIRFLOW_CTX_EXECUTION_DATE='2025-03-21T17:59:13.800189+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-21T17:59:13.800189+00:00'
[2025-03-21T17:59:25.167+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-21T17:59:26.125+0000] {python.py:240} INFO - Done. Returned value was:                                    id  ...                 created_at
0    c78187099ce1eac2fd7922d2d53948db  ... 2025-03-21 17:59:25.867680
1    b2bd0b3c4f0bd33f962b5e887ea4390d  ... 2025-03-21 17:59:25.870600
2    52390f6615815f3a4a42b453eb76363c  ... 2025-03-21 17:59:25.872437
3    be071f2658179672c42d0ee26ebd5c37  ... 2025-03-21 17:59:25.874196
4    c9e6fb6e4fd2091d238b86547401e76a  ... 2025-03-21 17:59:25.876658
..                                ...  ...                        ...
116  6f7f1689a49291a3152174e43e615989  ... 2025-03-21 17:59:26.105701
117  51229e011e66c3495a4c592cb2a4aa72  ... 2025-03-21 17:59:26.106811
118  24429a9906b22dde77071262f18c9965  ... 2025-03-21 17:59:26.108051
119  12fa5684f2a179a22ddc8a7aba189067  ... 2025-03-21 17:59:26.109198
120  5a86237697e6f0ae9fb2d1be0c98bbe2  ... 2025-03-21 17:59:26.110421

[121 rows x 6 columns]
[2025-03-21T17:59:26.300+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-21T17:59:26.301+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=weather-two-source, task_id=fetch_weather_tomorrow, run_id=manual__2025-03-21T17:59:13.800189+00:00, execution_date=20250321T175913, start_date=20250321T175924, end_date=20250321T175926
[2025-03-21T17:59:26.391+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-21T17:59:26.789+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-21T17:59:26.792+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
