[2025-03-21T19:05:02.396+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-21T19:05:02.463+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather-data-pipeline.fetch_weather_tomorrow manual__2025-03-21T19:04:56.298692+00:00 [queued]>
[2025-03-21T19:05:02.492+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather-data-pipeline.fetch_weather_tomorrow manual__2025-03-21T19:04:56.298692+00:00 [queued]>
[2025-03-21T19:05:02.494+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-21T19:05:02.544+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): fetch_weather_tomorrow> on 2025-03-21 19:04:56.298692+00:00
[2025-03-21T19:05:02.622+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1464) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-21T19:05:02.686+0000] {standard_task_runner.py:72} INFO - Started process 1477 to run task
[2025-03-21T19:05:02.643+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather-data-pipeline', 'fetch_weather_tomorrow', 'manual__2025-03-21T19:04:56.298692+00:00', '--job-id', '140', '--raw', '--subdir', 'DAGS_FOLDER/weather-data-pipeline.py', '--cfg-path', '/tmp/tmpth5erdag']
[2025-03-21T19:05:02.721+0000] {standard_task_runner.py:105} INFO - Job 140: Subtask fetch_weather_tomorrow
[2025-03-21T19:05:03.162+0000] {task_command.py:467} INFO - Running <TaskInstance: weather-data-pipeline.fetch_weather_tomorrow manual__2025-03-21T19:04:56.298692+00:00 [running]> on host c25e9da6226b
[2025-03-21T19:05:20.585+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather-data-pipeline' AIRFLOW_CTX_TASK_ID='fetch_weather_tomorrow' AIRFLOW_CTX_EXECUTION_DATE='2025-03-21T19:04:56.298692+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-21T19:04:56.298692+00:00'
[2025-03-21T19:05:20.607+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-21T19:05:27.111+0000] {python.py:240} INFO - Done. Returned value was:                datetime  ...                                id
0   2025-03-21 19:00:00  ...  fc5084a93de4b44f9bcd3f4dabf3a246
1   2025-03-21 20:00:00  ...  c3fcd16407cf6889274f95f7901da387
2   2025-03-21 21:00:00  ...  49bba3c3abf918a63c7a3a280494bbb5
3   2025-03-21 22:00:00  ...  f710bb6389cb3585aa7ee83fbb77578e
4   2025-03-21 23:00:00  ...  5fffff7f34aece608054205114f9cf26
..                  ...  ...                               ...
116 2025-03-26 15:00:00  ...  c26bfc4a28d0fe1d43d73ca7406a462c
117 2025-03-26 16:00:00  ...  bade1d9be667b9a0c85baabae88cbf30
118 2025-03-26 17:00:00  ...  c815a1943112db8980f44034d9bc2fbc
119 2025-03-26 18:00:00  ...  72db1191d1a9970f9e337937fe6e1b3d
120 2025-03-26 19:00:00  ...  5835a17b9c49075ebeb71a1b3d8a9fcf

[121 rows x 6 columns]
[2025-03-21T19:05:27.444+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-21T19:05:27.446+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=weather-data-pipeline, task_id=fetch_weather_tomorrow, run_id=manual__2025-03-21T19:04:56.298692+00:00, execution_date=20250321T190456, start_date=20250321T190502, end_date=20250321T190527
[2025-03-21T19:05:27.699+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-21T19:05:27.816+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
